export const achievementsData = [
  {
    id: 1,
    title: "CompTIA Security+",
    issuer: "CompTIA",
    date: "In Progress",
    credentialId: "SY0-XXX-XXX",
    description: "Foundational cybersecurity certification covering network security, compliance, and operational security.",
    status: "in-progress",
    icon: "shield",
    color: "#00d4ff",
  },
  {
    id: 2,
    title: "eJPT (eLearnSecurity Junior Penetration Tester)",
    issuer: "INE Security",
    date: "Planned",
    credentialId: "",
    description: "Practical penetration testing certification focusing on real-world offensive security skills.",
    status: "planned",
    icon: "bug",
    color: "#ff4757",
  },
  {
    id: 3,
    title: "CEH (Certified Ethical Hacker)",
    issuer: "EC-Council",
    date: "Planned",
    credentialId: "",
    description: "Comprehensive ethical hacking certification covering penetration testing methodologies.",
    status: "planned",
    icon: "terminal",
    color: "#f97316",
  },
  {
    id: 4,
    title: "CTF Challenges Completed",
    issuer: "TryHackMe / HackTheBox",
    date: "Ongoing",
    credentialId: "",
    description: "Completed numerous CTF challenges across web, crypto, forensics, and exploitation categories.",
    status: "completed",
    icon: "trophy",
    color: "#00ff88",
  },
  {
    id: 5,
    title: "Bug Bounty Reports",
    issuer: "HackerOne / Bugcrowd",
    date: "Ongoing",
    credentialId: "",
    description: "Submitted vulnerability reports to various bug bounty programs.",
    status: "completed",
    icon: "award",
    color: "#79c0ff",
  },
];
