import {
  SiLinux,
  SiPython,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiGit,
  SiGithub,
  SiWireshark,
  SiMetasploit,
  SiBurpsuite,
  SiOwasp,
  SiVirtualbox,
  SiDocker,
} from "react-icons/si";
import {
  FaShieldAlt,
  FaBug,
  FaSearch,
  FaNetworkWired,
  FaTerminal,
  FaLock,
  FaCode,
  FaDatabase,
  FaNetworkWired as FaNmap,
} from "react-icons/fa";

export const skillsData = {
  offensive: {
    title: "Offensive Security",
    icon: FaBug,
    color: "#ff4757",
    skills: [
      { name: "Penetration Testing", level: 90 },
      { name: "Web App Security", level: 92 },
      { name: "Bug Bounty Hunting", level: 85 },
      { name: "Exploit Development", level: 75 },
      { name: "Social Engineering", level: 70 },
      { name: "Network Attacks", level: 88 },
    ],
  },
  defensive: {
    title: "Defensive Security",
    icon: FaShieldAlt,
    color: "#00ff88",
    skills: [
      { name: "Incident Response", level: 85 },
      { name: "Threat Analysis", level: 82 },
      { name: "Security Monitoring", level: 88 },
      { name: "Malware Analysis", level: 70 },
      { name: "Digital Forensics", level: 75 },
      { name: "Risk Assessment", level: 80 },
    ],
  },
  osint: {
    title: "OSINT & Research",
    icon: FaSearch,
    color: "#00d4ff",
    skills: [
      { name: "OSINT Techniques", level: 90 },
      { name: "Threat Intelligence", level: 85 },
      { name: "Dark Web Research", level: 75 },
      { name: "Investigation Tools", level: 88 },
      { name: "Data Analysis", level: 80 },
      { name: "Recon Methods", level: 92 },
    ],
  },
  networking: {
    title: "Networking",
    icon: FaNetworkWired,
    color: "#f97316",
    skills: [
      { name: "TCP/IP", level: 90 },
      { name: "DNS", level: 88 },
      { name: "Firewalls", level: 85 },
      { name: "Packet Analysis", level: 92 },
      { name: "Network Security", level: 87 },
      { name: "Wireless Security", level: 80 },
    ],
  },
};

export const toolsData = [
  { name: "Linux", icon: SiLinux, color: "#fcc624", category: "OS" },
  { name: "Kali Linux", icon: SiLinux, color: "#557c94", category: "OS" },
  { name: "Python", icon: SiPython, color: "#3776ab", category: "Language" },
  { name: "JavaScript", icon: SiJavascript, color: "#f7df1e", category: "Language" },
  { name: "HTML5", icon: SiHtml5, color: "#e34f26", category: "Language" },
  { name: "CSS3", icon: SiCss, color: "#1572b6", category: "Language" },
  { name: "Git", icon: SiGit, color: "#f05032", category: "Tool" },
  { name: "GitHub", icon: SiGithub, color: "#ffffff", category: "Tool" },
  { name: "Nmap", icon: FaNmap, color: "#48a857", category: "Security" },
  { name: "Metasploit", icon: SiMetasploit, color: "#1f9f00", category: "Security" },
  { name: "Burp Suite", icon: SiBurpsuite, color: "#ff6633", category: "Security" },
  { name: "Wireshark", icon: SiWireshark, color: "#1679a7", category: "Security" },
  { name: "OWASP ZAP", icon: SiOwasp, color: "#ff4757", category: "Security" },
  { name: "Docker", icon: SiDocker, color: "#2496ed", category: "Tool" },
  { name: "VirtualBox", icon: SiVirtualbox, color: "#2173d7", category: "Tool" },
  { name: "Terminal", icon: FaTerminal, color: "#00d4ff", category: "Tool" },
  { name: "Security Analysis", icon: FaLock, color: "#00ff88", category: "Security" },
  { name: "Scripting", icon: FaCode, color: "#79c0ff", category: "Language" },
  { name: "Database", icon: FaDatabase, color: "#f97316", category: "Tool" },
];
