import { useState, useMemo } from 'react'
import { motion } from 'framer-motion'
import { FiFileText, FiDownload, FiPrinter } from 'react-icons/fi'

export default function ReportGenerator({ onAnalysis }) {
  const [reportData, setReportData] = useState({
    target: '',
    scope: '',
    findings: '',
    recommendations: '',
  })

  const reportContent = useMemo(() => {
    if (!reportData.target && !reportData.findings) return null
    return `
===============================================
       SECURITY ANALYSIS REPORT
===============================================

Target:       ${reportData.target || 'Not specified'}
Scope:        ${reportData.scope || 'General assessment'}
Date:         ${new Date().toLocaleDateString()}
Analyst:      Automated Security Tool

===============================================
FINDINGS
===============================================

${reportData.findings || 'No findings documented.'}

===============================================
RECOMMENDATIONS
===============================================

${reportData.recommendations || 'No recommendations documented.'}

===============================================
DISCLAIMER
===============================================

This report is generated based on documented findings
and verified data only. No simulated, fabricated, or
unverified data is included.

Generated by Security Analysis Dashboard
===============================================
    `.trim()
  }, [reportData])

  const handleDownload = () => {
    if (!reportContent) return
    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `security-report-${reportData.target || 'unnamed'}-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    onAnalysis({ tool: 'Report Generator', riskLevel: 'info', target: reportData.target || 'Report' })
  }

  const handlePrint = () => {
    if (!reportContent) return
    try {
      const printWindow = window.open('', '_blank')
      if (!printWindow) {
        alert('Popup blocked. Please allow popups for this site.')
        return
      }
      // Report fields are free text, so escape before injecting into the document.
      const escaped = reportContent
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
      printWindow.document.write(
        `<!DOCTYPE html><html><head><title>Security Report</title></head>` +
        `<body style="margin:0;background:#fff;">` +
        `<pre style="font-family: monospace; padding: 20px; color: #111; white-space: pre-wrap;">${escaped}</pre>` +
        `</body></html>`
      )
      printWindow.document.close()
      printWindow.focus()
      // Give the new document a tick to lay out before the print dialog opens.
      // Whether onload still fires after document.write depends on the engine,
      // so both paths are kept but only the first one through wins — otherwise
      // the visitor gets two stacked print dialogs.
      let printed = false
      const printOnce = () => {
        if (printed) return
        printed = true
        printWindow.print()
      }
      printWindow.onload = printOnce
      setTimeout(printOnce, 250)
    } catch {
      alert('Failed to open print window.')
    }
  }

  return (
    <div className="glass-card p-5 sm:p-8">
      <h3 className="text-xl font-semibold text-cyber-white mb-3">Report Generator</h3>
      <p className="text-sm text-cyber-muted mb-8">Generate professional security analysis reports from verified findings.</p>

      <div className="space-y-5 mb-8">
        <div>
          <label className="block text-xs text-cyber-muted mb-1.5">Target</label>
          <input
            type="text"
            value={reportData.target}
            onChange={(e) => setReportData(prev => ({ ...prev, target: e.target.value }))}
            placeholder="e.g., example.com, 192.168.1.1"
            className="input-field"
          />
        </div>
        <div>
          <label className="block text-xs text-cyber-muted mb-1.5">Scope</label>
          <input
            type="text"
            value={reportData.scope}
            onChange={(e) => setReportData(prev => ({ ...prev, scope: e.target.value }))}
            placeholder="e.g., External penetration test, SSL audit"
            className="input-field"
          />
        </div>
        <div>
          <label className="block text-xs text-cyber-muted mb-1.5">Findings</label>
          <textarea
            value={reportData.findings}
            onChange={(e) => setReportData(prev => ({ ...prev, findings: e.target.value }))}
            placeholder="Document verified security findings here..."
            rows={5}
            className="input-field resize-none"
          />
        </div>
        <div>
          <label className="block text-xs text-cyber-muted mb-1.5">Recommendations</label>
          <textarea
            value={reportData.recommendations}
            onChange={(e) => setReportData(prev => ({ ...prev, recommendations: e.target.value }))}
            placeholder="Document defensive recommendations..."
            rows={4}
            className="input-field resize-none"
          />
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 mb-8">
        <button onClick={handleDownload} disabled={!reportContent} className="btn-primary flex items-center justify-center gap-2 disabled:opacity-40 shrink-0">
          <FiDownload className="w-4 h-4" />
          Download Report
        </button>
        <button onClick={handlePrint} disabled={!reportContent} className="btn-secondary flex items-center justify-center gap-2 disabled:opacity-40 shrink-0">
          <FiPrinter className="w-4 h-4" />
          Print
        </button>
      </div>

      {reportContent && (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
          <div className="p-4 rounded-xl bg-cyber-dark/70 border border-cyber-border/30">
            <div className="flex items-center gap-2 mb-3">
              <FiFileText className="w-4 h-4 text-cyber-cyan" />
              <span className="text-xs font-semibold text-cyber-white">Report Preview</span>
            </div>
            <pre className="text-xs text-cyber-muted font-mono whitespace-pre-wrap overflow-auto max-h-64 scrollbar-thin">
              {reportContent}
            </pre>
          </div>
        </motion.div>
      )}

      {!reportContent && (
        <div className="text-center py-8 text-cyber-muted/50">
          <FiFileText className="w-8 h-8 mx-auto mb-2" />
          <p className="text-xs">Fill in the fields above to generate a report</p>
        </div>
      )}
    </div>
  )
}
